### ISSUE TITLE
Build: libRealSensePlugin.so install path

### ISSUE THREAD

**Issue by mbelluzzo** [01org/collision-avoidance-library#41]
It disregards CMAKE_INSTALL_PREFIX during 'make install'

**Comment by mbelluzzo** [comment]
It will be solved by #90

**Comment by anselmolsm** [comment]
By "solved" here you mean transferred to gazebo-realsense, right? ;)

**Comment by mbelluzzo** [comment]
No, truly solved. It was a problem to broadcast variables values between
both cmake builds that wont happen anymore.

On Tue, Mar 7, 2017 at 4:43 PM, Anselmo L. S. Melo <notifications@github.com

**Comment by avinash-palleti** [comment]
@anselmolsm Hope this is solved as #90 is closed and merged.
