### ISSUE TITLE
Wiki: Tutorial about how to write a detector and an avoidance

### ISSUE THREAD

**Issue by mbelluzzo** [01org/collision-avoidance-library#62]
- [ ] How to write a Detector
- [ ] How to write an Avoidance

- Bonus round: How to write a sensor?

**Comment by mbelluzzo** [comment]
I saw that you wrote a tutorial about the coav app structure (which is looking nice), but I didnt find a way to track all wiki changes on all pages in a easy form. So once update the wiki with this information, plz ping a comment here so we know.

**Comment by rchiossi** [comment]
Actually I had a single tutorial with everything but I decided to split it into two. I'm clearing the code for the second now.
BTW, I'm using git to edit the wiki, not the online editor. Using git directly gives cleaner revisions.

**Comment by mbelluzzo** [comment]
Yeah, it does, but I miss the preview :-/

**Comment by rchiossi** [comment]
I push it to my fork to see the preview
